context:
  version: "8.1.0"

package:
  name: libzeep
  version: ${{ version }}

source:
  url: https://forge.hekkelman.net/maarten/zeep/archive/v${{ version }}.tar.gz
  sha256: 1aa63b3dc10de06ba56faa2655345a0a72617b323be39c06e1fa226016f40ab4
build:
  number: 0
  script:
    - sed -i -E 's#ssl::rfc2818_verification\(#ssl::host_name_verification(#g' src/client.cpp

    - if: unix
      then: |
        set -exo pipefail
        export CXXFLAGS="${CXXFLAGS} -D_LIBCPP_DISABLE_AVAILABILITY"
        cmake -S . -B build -G Ninja \
          ${CMAKE_ARGS} \
          -DBUILD_SHARED_LIBS=ON \
          -DZEEP_USE_BOOST_ASIO=OFF
        cmake --build build --parallel ${CPU_COUNT}
        if [[ "${target_platform}" == "linux-aarch64" || "${target_platform}" == "linux-ppc64le" ]]; then
          ctest -V --test-dir build -E "(http-test|daemon-test)"
        fi
        cmake --install build
    - if: win
      then: |
        @echo on
        sed -i "/^#include <signal.h>$/i #include <exception>" src/signals.cpp || exit /b 1
        sed -i "/^#include <signal.h>$/a using std::exception;" src/signals.cpp || exit /b 1
        > sed_script.txt (
          echo /auto r = std::from_chars(c + 1, c + 3, value, 16);/c^\
          echo const char* base = s.data();
          echo const auto offset = c - s.begin();
          echo auto r = std::from_chars(base + offset + 1, base + offset + 3, value, 16);
        )
        sed -i -f sed_script.txt src/uri.cpp
        del sed_script.txt
        sed -i -E "s#r\.ptr == c \+ 3#r.ptr == base + offset + 3#" src/uri.cpp
        cmake -S . -B build -G Ninja ^
          %CMAKE_ARGS% ^
          -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON ^
          -DBUILD_SHARED_LIBS=ON ^
          -DZEEP_USE_BOOST_ASIO=OFF ^
          || exit /b 1
        cmake --build build --parallel %CPU_COUNT% || exit /b 1
        set PATH=%CD%\build\bin;%CD%\build\lib;%PATH%
        @REM Run tests, excluding the HTTP test which brings about a SEGFAULT error
        ctest -V -C Release --test-dir build -E "http-test" || exit /b 1
        cmake --install build || exit /b 1

requirements:
  build:
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - ${{ "clang-tools" if osx }}
    - ${{ "m2-sed" if win else "sed" }}
    - cmake
    - ninja
    - pkg-config
  host:
    - asio
    - catch2
    - howardhinnant_date
    - libzeem
    - ${{ "maartens_resource_compiler" if linux }}
    - nlohmann_json
    - openssl
  run_exports:
    - ${{ pin_subpackage("libzeep", upper_bound="x") }}
  ignore_run_exports:
    from_package:
      - catch2

tests:
  - package_contents:
      include:
        - zeep/*
      lib:
        - zeep

about:
  homepage: https://mhekkel.github.io/libzeep
  repository: https://forge.hekkelman.net/maarten/zeep
  documentation: https://mhekkel.github.io/libzeep
  license: BSD-2-Clause AND BSL-1.0
  license_file: LICENSES/
  summary: "C++ library for reading and writing XML and creating web, REST and SOAP servers"
  description: |
    Libzeep is a web application framework written in C++.
    To see a starter project visit the [libzeep-webapp-starter](https://github.com/mhekkel/libzeep-webapp-starter.git) page.

extra:
  recipe-maintainers:
    - eunos-1128
